---
title: "STA 463 Project"
author: "Justus Thomas"
date: "5/2/2022"
output: html_document
---

```{r}
library(readxl)
nbadata <- read_xlsx("basketball-1.xlsx")
```

## Each report should set out to do one of two things:

1. Confirmatory multiple linear regression. Thoroughly address at least one research hypothesis or research question that is formed based on the description of the data or an initial exploration of it. This analysis can involve any hypothesis that can be tested using the methods we’ve developed.
2. Predictive model. If the dataset you choose is large enough, you may develop a predictive model using approaches like training/test sets or cross-validation. The analysis should include an assessment of the quality of the model to predict out-of-sample data. Ideally, it would also include predictions for one or two interesting new data points. (This topic will be addressed after the exam.)

## Introduction
Include a description of your hypothesis/question or predictive approach, as well as a basic description of the dataset and the variables of interest.

(Choose your hypothesis/goal carefully, because not all hypotheses will lend themselves to easy analysis. What are the tools we’ve developed so far? We can do tests on hypotheses regarding single parameters or groups of parameters. We can form models with interactions and/or higher-order terms. We can predict future observations and analyze the average response value for a particular set of predictors. Perhaps a few other things I haven’t mentioned. Can your hypothesis/goal be answered by a method we have developed?)

## Exploratory Data Analysis (EDA)
come after the introduction, and consist of plots (i.e. scatterplots) and/or tabular summaries of the raw data (for example: means and standard deviations of X and Y). The purpose of the EDA is to familiarize you and the reader with the data and to derive insight from the initial analysis. You should include some concise commentary about what you learned from the EDA.

## Analysis
state the model (or models) you will fit and the process (if any) you used to come to a final model. Include only output that is relevant. You should also check the assumptions of the model, and if they are seriously violated you should take appropriate remedial measures if possible.

## Conclusion
communicate in clear terms the results of your analysis as they pertain to your original research hypothesis. Was it confirmed or was there a lack of evidence? Are you making your conclusion in a way that does not include unnecessary statistical jargon?
